# build environment
FROM node:lts-alpine
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
ENV PORT 80

COPY package.json ./
COPY package-lock.json ./
COPY public ./public
COPY src ./src
RUN npm ci
RUN npm install

EXPOSE 80
CMD ["npm", "start"]
