apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: note-app
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: notebook/note-app
      docker:
        dockerfile: Dockerfile.dev
profiles:
  - name: production
    build:
      tagPolicy:
        gitCommit:
          prefix: production-
      artifacts:
        - image: notebook/note-app
          docker:
            dockerfile: Dockerfile.prod
  - name: staging
    build:
      tagPolicy:
        gitCommit:
          prefix: staging-
      artifacts:
        - image: notebook/note-app
          docker:
            dockerfile: Dockerfile.prod